### ISSUE TITLE
Source in repo != source used in repo jar

### ISSUE THREAD

**Issue by ghost** [reficio/soap-ws#15]
Hi!

I just looked in the soap-client.jar that maven pulls. The SoapClient class isn't the one in the repo. In git, the DefaultHTTPClient is initialized when the SoapClient is built. In the jar file, the DefaultHTTPClient is redone whenever a POST is done.

That means that it's impossible to add an interceptor or manipulate the HTTP client before the POST goes out. It also makes HTTP sessions impossible.

Is the JAR source and older version that hasn't been updated to the git version, or a new source that hasn't had its source checked in yet?

**Comment by tombujok** [comment]
Hi, it's possible. The deploy build has failed: https://reficio.ci.cloudbees.com/job/soap-ws-deploy/
If you have time, could you have a look why the test is failing?

**Comment by ghost** [comment]
Looks like SimpleClientTest is trying to connect to test.ch, which doesn't exist anymore.

**Comment by tombujok** [comment]
pull request with fix appreciated ;)

## 

Tom Bujok
Reficio™ - Reestablish your software!
http://www.reficio.org

**Comment by tombujok** [comment]
Should be fine. The artifacts have been just deployed to the repo.
