### ISSUE TITLE
Maven dependency not working?

### ISSUE THREAD

**Issue by javadan** [reficio/soap-ws#2]
Hi Tom,

Came here from the stackoverflow programmatic soap-ui question.  Don't have enough karma points to ask there.  

When trying to get your code via Maven-3.0.4, using the 3 dependencies, (I added reficio to settings.xml), I get this error:

maven-metadata-reficio.xml.error=Could not transfer metadata com.centeractive:soap-client:1.0.0-SNAPSHOT/maven-metadata.xml from/to reficio (http://repo.reficio.org/maven/): connection timed out to http://repo.reficio.org/maven/com/centeractive/soap-client/1.0.0-SNAPSHOT/maven-metadata.xml

Is this an issue on my side?  Maybe a proxy error?  I tried adding the proxy settings and restarting Eclipse but nope.

-Dan

I think it must just be a proxy error.  Nm.

**Comment by tombujok** [comment]
Hi Dan, 

Thanks for closing this issue. I was thinking that it's not a soap-ws problem, but did not have time to doublecheck.

Tom

**Comment by javadan** [comment]
Hey Tom, 

It was definitely some proxy thing, which I gave up on. I decided to copy in the code to my project directly, and it's working now.  I did have to make some changes, as the resource loading wasn't working.  I think it's because it is usually in a jar file, but now it's part of my project: 

URL soapEncodingXmlResource = ResourceUtils.getResourceWithAbsolutePackagePath(getClass(), "/xsds/", "soapEncoding12.xsd");
changed to:
URL soapEncodingXmlResource = new URL("file:///" + System.getProperty("user.dir") + "/xsds/soapEncoding12.xsd");

Thanks for taking the time to extract SOAP-UI's code.  I couldn't get their maven stuff to build either :/

Regards,
Daniel

**Comment by tombujok** [comment]
This should not be like this - I mean the resources.
This works correctly for many people.
What OS and JVM are you using?

**Comment by javadan** [comment]
Windows 7, Java 6...  

Well check javadoc: http://commons.apache.org/io/api-2.0/org/apache/commons/io/FilenameUtils.html#normalizeNoEndSeparator%28java.lang.String%29 

the resource location /xsds/myxsd.xsd will refer to a path starting with a /.  That won't work on a Windows machine.  In Linux, I think it means a folder in the root directory.  But for a relative path, you can't put a / in front.
