### ISSUE TITLE
run example error

### ISSUE THREAD

**Issue by xunchangguo** [reficio/soap-ws#23]
use example
Wsdl wsdl = Wsdl.parse("http://www.webservicex.net/CurrencyConvertor.asmx?WSDL");

```
    SoapBuilder builder = wsdl.binding()
        .localPart("CurrencyConvertorSoap")
        .find();
    SoapOperation operation = builder.operation()
        .soapAction("http://www.webserviceX.NET/ConversionRate")
        .find();
    String request = builder.buildInputMessage(operation);
    SoapClient client = SoapClient.builder()
        .endpointUri("http://www.webservicex.net/CurrencyConvertor.asmx")
        .build();
    String response = client.post(request);
    System.out.println(response);
```

get fatal error:

[CLOVER] FATAL ERROR: Clover could not be initialised. Are you sure you have Clover in the runtime classpath? (class java.lang.NoClassDefFoundError:com_cenqua_clover/CloverVersionInfo)
Exception in thread "main" java.lang.NoClassDefFoundError: com_cenqua_clover/CoverageRecorder
    at org.reficio.ws.builder.core.Wsdl.parse(Wsdl.java:68)
    at demo.WsdlTest.main(WsdlTest.java:12)

why? any thing wrong?

**Comment by tombujok** [comment]
Where did you take the binaries (jars) from? It looks like the version was build with clover instrumentation :(

**Comment by xunchangguo** [comment]
from this https://reficio.ci.cloudbees.com/job/soap-ws/ws/

**Comment by xunchangguo** [comment]
with source build, it is ok, thank u!
